apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    env: dev
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      env: dev
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        env: dev
    spec:
      initContainers:
      - name: busyboxi
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c","chmod -R 777 /data"]
        volumeMounts:
        - name: "{{ .Release.Name }}-rpc-moonbasealpha-claim"
          mountPath: "/data"
      # - name: busybox
      #   image: busybox:latest
      #   args:
      #   - sleep
      #   - "3600"
      containers:
      # - name: busybox
      #   image: busybox:latest
      #   args:
      #   - sleep
      #   - "3600"
      #   volumeMounts:
      #   - name: "{{ .Release.Name }}-rpc-moonbasealpha-claim"
      #     mountPath: "/data"
      - name: {{ .Release.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        args:
          -  --base-path=/data
          - --chain=alphanet 
          - --name={{ .Values.nodeName }} 
          - --execution=wasm 
          - --wasm-execution=compiled 
          - --pruning=archive 
          - --state-cache-size=0 
          - -- 
          - --execution=wasm 
          - --pruning=1000 
          - --name={{ .Values.nodeName }}
        volumeMounts:
          - name: "{{ .Release.Name }}-rpc-moonbasealpha-claim"
            mountPath: /data
      volumes:
      - name: "{{ .Release.Name }}-rpc-moonbasealpha-claim"
        persistentVolumeClaim:
          claimName: "{{ .Release.Name }}-rpc-moonbasealpha-claim"

