apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-rpc-moonbasealpha-claim"
  labels:
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageclass }}
  resources:
    requests:
      storage: 1000Gi