apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rpc-moonbasealpha-claim
  labels:
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 500Gi