apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkins.fullname" . }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ printf "%s-%s" .Release.Name "jenkins" }}
  type: ClusterIP